updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    groups:
      tailwindcss:
        applies-to: version-updates
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/postcss'
      nextjs:
        applies-to: version-updates
        patterns:
          - '@next/*'
          - 'eslint-config-next'
          - '@types/react'
          - '@types/react-dom'
          - 'next'
      auth:
        applies-to: version-updates
        patterns:
          - 'better-auth'
      prisma:
        applies-to: version-updates
        patterns:
          - 'prisma'
          - '@prisma/client'
          - '@prisma/adapter-pg'
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: '@aws-sdk/client-lambda'
      - dependency-name: '@aws-sdk/client-s3'
      - dependency-name: '@aws-sdk/s3-request-presigner'
      - dependency-name: 'sharp'
      - dependency-name: 'autosize'
      - dependency-name: '@types/node'
      - dependency-name: '@types/react'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
version: 2
