jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_DB: annostamps
          POSTGRES_PASSWORD: annouser
          POSTGRES_USER: annouser
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - env:
          DATABASE_URL: postgresql://annouser:annouser@localhost:5433/annostamps
          DIRECT_URL: postgresql://annouser:annouser@localhost:5433/annostamps

        name: Create Database and Seed
        run: pnpm migrate && pnpm db-seed
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          configuration: DEBUG=1
          image-tag: 4.7.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/dev
      - env:
          AWS_ACCESS_KEY_ID: test
          AWS_S3_BUCKET: annostamps
          AWS_S3_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: test
          BETTER_AUTH_SECRET: f2mwGCORoYHFR9ZZRNqx2y5SEPraT8ML
          BETTER_AUTH_URL: http://localhost:3000
          DATABASE_URL: postgresql://annouser:annouser@localhost:5433/annostamps
          NEXT_PUBLIC_CLOUDFRONT_CDN: http://s3.localhost.localstack.cloud:4566/annostamps
        name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: pnpm build
          start: pnpm start
    timeout-minutes: 15
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run lint
        run: pnpm lint
  test:
    name: test_front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run test
        run: pnpm test
name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main
